#pragma once
#include "Common.h"
namespace stu
{
	/// <summary>
	/// A shader program has a function that returns the ID that was generated by OpenGl
	/// </summary>
	class IShaderProgram
	{
	public:
		virtual GLuint GetId() = 0;
	};
}
